### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by jaydson** [braziljs/braziljs-api#1]
We have an encoding issue with the API.

URL: https://braziljs.org/api/list/events
Response:
![screenshot from 2016-05-10 14 18 52](https://cloud.githubusercontent.com/assets/72206/15155719/2e87799a-16ba-11e6-95a3-aee14930065c.png)

//cc @felipenmoura

**Comment by felipenmoura** [comment]
Thanks for reporting.

Fixed.
